---
author: 'Mehmet Başal'
description: ''
email: 'mhmtbsl@bil.omu.edu.tr'
url: 'fo.pasali.co'
domain: 'pasali.co'
intro: ''
googleanalytics: ''
googleplus: ''
brand: default
landslide: /usr/bin/landslide
css: _/default.css
js: _/default.js
theme: light
indextemplate: _/index.erb
foliotemplate: _/default.erb
