---
author: 'pasali'
description: ''
email: 'mhmtbsl@bil.omu.edu.tr'
url: 'mhmtbsl.net'
domain: ''
intro: ''
googleanalytics: ''
googleplus: ''
brand: default
landslide: /usr/bin/landslide
css: _/default.css
js: _/default.js
theme: light
indextemplate: _/index.erb
foliotemplate: _/default.erb
